config/routes.rb
EasyOpenSource::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  devise_for :users
  resources  :projetos 
  resources  :items
  resources  :caixas
  resources  :qualificacaos
  resources  :forem 

  get  'static_pages/home', as: :home
  root 'static_pages#home'
  
  get 'qualificacaos/technical_skills'     => 'qualificacaos#technical_skills', as: :technical_skills
  get 'qualificacaos/soft_skills'          => 'qualificacaos#soft_skills', as: :soft_skills
  get 'qualificacaos/resources_available'  => 'qualificacaos#resources_available', as: :resources_available

  get 'pagina_projeto'  => 'projetos#pagina_projeto', as: :paginas_projeto
  get 'projetos/index'  => 'projetos#index', as: :projetos_path
  get 'projetos/search' => 'projetos#search', as: :projetos_search

  

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
	has_many  :users
  has_many  :box_projects
  validates :nome, presence: true

    # Para guardar arquivos no DropBox. O arquivo dropbox.yml contém as senhas do dropbox
	has_attached_file   :arquivoproj,
                      :storage => :dropbox,
                      :dropbox_credentials => Rails.root.join("config/dropbox.yml")

  do_not_validate_attachment_file_type :arquivoproj

    # busca avançada, por enquanto não está sendo utilizada
    def self.procura_projeto(linguagem, os, ide, repositorio, database)
    return scoped unless linguagem.present? || os.present? ||  ide.present? || repositorio.present? || 
                         database.present?
        where(['linguagem LIKE ? OR os LIKE ? OR ide LIKE ? 
                 OR repositorio LIKE ? OR database LIKE ?', 
                "%#{linguagem}%", "%#{os}%", "%#{ide}%", "%#{repositorio}%", "%#{database}%"])
    end

end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]

  # GET /projetos
  # GET /projetos.json

  # GET /index
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
    @query = params[:q]
    @projetos = []
    if @query == ""
       redirect_to action: "show"
    else
      if @query == "ADD" or @query == "add"
         redirect_to action: "new"
      else @projetos = Projeto.where('nome LIKE ?', "%#{@query}%")
      end
    end 
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
  end

  # GET /projetos/1/edit
  def edit
  end

  # GET /projetos/contribuir
  def contribuir
  end

  def lista_projetos
  end

  # GET /pagina_projeto
  def pagina_projeto    
  end

  def search
    @query = params[:q]
    @projetos = []
    if @query == ""
      redirect_to :back
    else
      @projetos = Projeto.where('nome LIKE ?', "%#{@query}%")
    end
  end 

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.create(projeto_params)  

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto criado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @projeto }
      else
        format.html { render action: 'new' }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto alterado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
      my_record = nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:nome, :descricao, :data_inicio, :status, :linguagem, :arquivoproj, :administrador, :os, :ide, :repositorio, :database, :urlPagina, :urlIssueTracker, :urlRepositorioFonte, :urlMailingList, :urlProjetoOpenHub, :licenca)
    end
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projetos/_form.html.erb
<%= form_for(@projeto, :url => projetos_path, :html => { :multipart => true  }) do |f| %>
<% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "erro") %> Impossível persistir dado:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="field">
    <%= f.text_field :nome, class: 'form-control', :placeholder => "Nome do Projeto"%>
  </div>
  <div class="field">
    <%= f.text_area :descricao , class: 'form-control', :placeholder => "Descrição do Projeto"%>
  </div>
  <div class="field">
    <%= f.text_area :licenca , class: 'form-control', :placeholder => "Licenças"%>
  </div>
  <div class="field">
    <%= f.url_field :urlPagina , class: 'form-control', :placeholder => "URL página do projeto"%>
  </div>
  <div class="field">
    <%= f.url_field :urlIssueTracker , class: 'form-control', :placeholder => "URL do issue tracker"%>
  </div>
  <div class="field">
    <%= f.url_field :urlRepositorioFonte , class: 'form-control', :placeholder => "URL do repositorio do fonte"%>
  </div>
  <div class="field">
    <%= f.url_field :urlMailingList , class: 'form-control', :placeholder => "URL da mailing list"%>
  </div>
  <div class="field">
    <%= f.url_field :urlProjetoOpenHub , class: 'form-control', :placeholder => "URL do projeto open hub"%>
  </div>
    <%= f.submit 'Incluir Projeto', class: 'btn btn-primary' %>
    <%= f.submit 'Limpar', :type => 'reset', class: 'btn btn-success' %>
<% end %>
     

app/views/projetos/edit.html.erb
<h1>Editar Projeto</h1>

<%= render 'form' %>

app/views/projetos/new.html.erb
<h4>Incluir Novo Projeto</h4>

<%= render 'form' %>
  

app/views/projetos/search.html.erb
<div class="">
	<% if @projetos.empty? %>
		<h1>Projeto não encontrado.</h1>
		<br>
		<p><%= "Usuário procurou por: '#{@query}'" %></p>
	<% else %>
		<h1><%= "Encontrado(s) #{@projetos.size} Projeto(s)." %></h1>
		<br>
		<p><%= "Usuário procurou por: '#{@query}'" %></p>
		<br>
		<h2>Projetos</h2>
		<%= render "projetos/lista_projetos" %>
	<% end %>
</div> 

app/views/projetos/show.html.erb
 </div>
 <table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
    </tr>
  </thead>

  <tbody>
    <% if not @projetos.empty? %>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= link_to projeto.nome, caixas_path %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>